travis:
  secure:
    BINSTAR_TOKEN: WYmFvNLznHuc7Y4EX83DdAuicKsAQUcHx3s/V/L5xKdCaqxvHLrfuhrBYfH3Jokfvlboj2BgFMB2egz/BzpIZc4vJD4m1CKJi+f6ae8x4NQNdTTI6S7PQwAXBskuAauK9ZANEghdHvFizKIq3wDtyBd5+Q2d2u+9+6Kyb7RzZsR4u384aH1/OjpVnkxZcHD0KT/UWQwUdQcJrPP2EnBDFOyJSuXx5wAKvTKCDM1oEM282iTg3D4dWp2grKWR+nyMF7vo/3JwvEbxpJ/P9EIG9CTivv83BfUFfXkkoyYC4o05aX+z57kZ4ZE5OD3o7upQ/M3GKKiMLEi2PKGI/jVhKQCBPTOedZsER1L+oSwyqUVYKWUQxd+9h+lsoKwHEbY1/IvVRrcx6InmU26nbMkpt1dh8UqSFKnZAYsAKVdWX5fq0Jj1kulthsRQ4jMui5Qu1CJT6SwK2WRaTsYOqHg61hvoNOkq0oW+6smqJgliLHdxamjtKxRfX9IUQSPtiaxcZeMOWKEqPi3ec1Og8zUZW0dCFtIiPQ4DgoNViJ931ewPtH4+T7Kzy/2NbhoTVcAn54rEc5VqvSfFfn9hfPY85m7YYIUvOLtyLxB/qpHSQ7FvSlRppmFB9pvzSIp0v6GrNuD1CirgOK1EyRqUppMS20W4p7ht56j2zB1IUF6RPOQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
