travis:
  secure:
    BINSTAR_TOKEN: wEWCO20JSnqg8NywEFCg2Zfi9QBLvOFMA6WgmoYXg5W8mr9OIstpBlbuJuzUhXJNIodb1s1PYrpTCzlzHfJ715Ky+7fTp/YHAOJPesLWZ3COMgaPWhyU/aXg/t8fK70sB1axWqvBgkP8O3wFpTHPbCDoMN9T8RoTC42CJATqJ+Ni4wyaaaYk8bxICcFvkDYRsRpkKyYUdWLdwB3BSsQz2nVnXnb71p7/G4Ga9vUYg29tFkEb/MiETZQ80lwvVJi9e8SGf3Yd/GtZR1YbQ7XUSfuMOjir91LpdxaSCAMnrVN/wHrVPYzHWD+nVXNn0v4QuI7rs60K4TTrIM+b2RNWQCw7tyOJvEiGSUSkoeIDh9gbGg4TxJYF7rapfcX+msLU3t7LC/aDNwK3qlhCtDEiw2aXwlvlYUIqSwMXHs1aTGP6OZ8A0aaBEps2C6fU1BW7BvZ/ty8zcJ+gB0WP39VokZLClDUYxJz1XAMJ3HWwvRzx/7CtYmnAEo8ryZa7KW7shyjobJoWocuAJl0qxkHVDWi+DFiYWc8jHI9K4srHxZjGm4H1hgRceP0WBYf5CAU9BJMuhpZd/W61Q4E5azUhcvoSI+zDDoLxSk3RRH/y3LMHEaVaLrNZjIBqJNkhOoOv0tWXEGi7Rj1il9kuHOLAR9x7DLBYY3Ca0uTJP5o64lg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
