travis:
  secure:
    BINSTAR_TOKEN: B8cN8J6/CTef9ZVAG1SDG1zGAJ9htWTLLz0GzkjWU6NzbnLQzGxPUO1651JfaH2uadPsijlp09zLt+IUQl0KvObPW3Hl0en93SrHsVVjokKrBMcz+SGZ0lPBSv1KEDA6wA6e0Xt0MWsGqWk/k1+9TeSgJNlck/Uv/hGnPMoIHYyngseXG4lJh2jZeMhBbild5KzgOGZSKPyZiH38wV1SQhDS5BKDEPkclNReLF5muso/Wu3no+lTwoF5pdzzCIaXoIZkmkEhDWVFfCgSZlAbAE9UDvnd9yCP2GD0XHgQ7e5XBlwO6uY8qyZ18WJOg3PAKj3Os+5cWVT0dUB0Vcg2vDtiaVwTuZ/XE7OZ+/qP4CZVlVUqvK+VsJVS93e3H4zgFu0WSgH1ECDIFeA7lZ56mXOnfjCK+n6K2E7s+eroNGbxRaAxaEtWQIDP3gHH9f+ZLT/Wu4NANS5+I+2GfF+nt7wnqAOUV2wfVfs/2bDbcu+wnU2fONe8ELyozeO8yYITgZZ5r5U3AGZU68xA3GMRQTn8vQcAC2bqHqy/UBExD/tOREPbcIPfJf4Kvl/12e8n5+ujhxqQmRcNlcrZzqNjKK4mvM4Gi0j1EY/ZPowKwA5L+c77gyksD/A3+QOzwsWE59ncVaYI6dNI3P/uWkA0sIz8MnhSNraTFIDtfptoq20=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
